id: I866B79AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:25:27+00:00'
last_modified: '2022-06-08T09:27:41.030914+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD224
  title: དངུལ་ཆུ་བཙོ་བཀྲུའི་ལག་ལེན་གསེར་ཞུན་ཐིག་ལེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    5E58:
      image_group_id: I2PD17891
      title: ''
      total_pages: 236
      order: 1
      base_file: 5E58.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
